export enum ExpertType {
  PHYTOPATHOLOGIST = 'PHYTOPATHOLOGIST',
  AGRONOMIST = 'AGRONOMIST',
  HYDRAULIC_ENGINEER = 'HYDRAULIC_ENGINEER',
  HYDROGEOLOGIST = 'HYDROGEOLOGIST',
  ZOOTECHNICIAN = 'ZOOTECHNICIAN',
  VETERINARY_EPIDEMIOLOGIST = 'VETERINARY_EPIDEMIOLOGIST',
}
