export enum ProfessionalStatus {
  CRDA_AGENT = 'CRDA_AGENT',
  LIBERAL = 'LIBERAL',
  CABINET_PRIVE = 'CABINET_PRIVE',
  COOPERATIVE = 'COOPERATIVE',
  ENSEIGNANT_CHERCHEUR = 'ENSEIGNANT_CHERCHEUR',
}
