export enum ContractStatus {
  DRAFT = 'DRAFT',
  OUVERTE = 'OUVERTE',
  EN_ATTENTE = 'EN_ATTENTE',
  NEGOTIATING = 'NEGOTIATING',
  NEGOCIATION = 'NEGOCIATION',
  EN_ATTENTE_SIGNATURE = 'EN_ATTENTE_SIGNATURE',
  ACCEPTED = 'ACCEPTED',
  ACTIF = 'ACTIF',
  IN_PROGRESS = 'IN_PROGRESS',
  EN_COURS = 'EN_COURS',
  COMPLETED = 'COMPLETED',
  TERMINEE = 'TERMINEE',
  DISPUTED = 'DISPUTED',
  CANCELLED = 'CANCELLED',
  ANNULEE = 'ANNULEE',
}

export const STATUS_TRANSITIONS: Record<ContractStatus, ContractStatus[]> = {
  [ContractStatus.DRAFT]:                [ContractStatus.OUVERTE, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.OUVERTE]:              [ContractStatus.EN_ATTENTE, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.EN_ATTENTE]:           [ContractStatus.NEGOCIATION, ContractStatus.NEGOTIATING, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.NEGOTIATING]:          [ContractStatus.EN_ATTENTE_SIGNATURE, ContractStatus.ACCEPTED, ContractStatus.ACTIF, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.NEGOCIATION]:          [ContractStatus.EN_ATTENTE_SIGNATURE, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.EN_ATTENTE_SIGNATURE]: [ContractStatus.ACTIF, ContractStatus.ACCEPTED, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.ACCEPTED]:             [ContractStatus.ACTIF, ContractStatus.EN_COURS, ContractStatus.IN_PROGRESS, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.ACTIF]:                [ContractStatus.EN_COURS, ContractStatus.IN_PROGRESS, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.IN_PROGRESS]:          [ContractStatus.EN_COURS, ContractStatus.COMPLETED, ContractStatus.TERMINEE, ContractStatus.DISPUTED, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.EN_COURS]:             [ContractStatus.TERMINEE, ContractStatus.COMPLETED, ContractStatus.DISPUTED, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.COMPLETED]:            [ContractStatus.TERMINEE, ContractStatus.DISPUTED],
  [ContractStatus.TERMINEE]:             [ContractStatus.DISPUTED],
  [ContractStatus.DISPUTED]:             [ContractStatus.COMPLETED, ContractStatus.TERMINEE, ContractStatus.CANCELLED, ContractStatus.ANNULEE],
  [ContractStatus.CANCELLED]:            [],
  [ContractStatus.ANNULEE]:              [],
};
