export enum ContractMessageType {
  TEXT = 'TEXT',
  OFFER = 'OFFER',
  COUNTER_OFFER = 'COUNTER_OFFER',
  SYSTEM = 'SYSTEM',
}

export enum DocumentType {
  WORK_ORDER = 'WORK_ORDER',
  DELIVERY_CONFIRMATION = 'DELIVERY_CONFIRMATION',
  RENTAL_AGREEMENT = 'RENTAL_AGREEMENT',
  INVOICE = 'INVOICE',
  RECEIPT = 'RECEIPT',
}

export enum DisputeReasonType {
  TRAVAIL_NON_CONFORME = 'TRAVAIL_NON_CONFORME',
  LIVRAISON_NON_EFFECTUEE = 'LIVRAISON_NON_EFFECTUEE',
  MATERIEL_ENDOMMAGE = 'MATERIEL_ENDOMMAGE',
  PAIEMENT_NON_RECU = 'PAIEMENT_NON_RECU',
  AUTRE = 'AUTRE',
}

export enum CancelledBy {
  FARMER = 'FARMER',
  PROVIDER = 'PROVIDER',
  SYSTEM = 'SYSTEM',
}
