export enum WalletTransactionType {
  MISSION_PENDING = 'MISSION_PENDING',
  RELEASED = 'RELEASED',
  CANCELLED_REFUND = 'CANCELLED_REFUND',
  CONSULTATION_PENDING = 'CONSULTATION_PENDING',
  CONSULTATION_RELEASED = 'CONSULTATION_RELEASED',
  AMBASSADOR_COMMISSION = 'AMBASSADOR_COMMISSION',
  WITHDRAWAL_REQUESTED = 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_COMPLETED = 'WITHDRAWAL_COMPLETED',
  ADJUSTMENT = 'ADJUSTMENT',
}
