export enum CertificateType {
  CAPACITE_PHYTOSANITAIRE = 'CAPACITE_PHYTOSANITAIRE',
  FORMATION_TRACTEUR = 'FORMATION_TRACTEUR',
  FORMATION_TAILLE = 'FORMATION_TAILLE',
  FORMATION_INAT = 'FORMATION_INAT',
  DIPLOME_LYCEE_AGRICOLE = 'DIPLOME_LYCEE_AGRICOLE',
  FORMATION_AVFA = 'FORMATION_AVFA',
  AUTRE = 'AUTRE',
}
